version: "3.7"

services:
  db:
    image: edgedb/edgedb
    container_name: ${PROJECT_NAME}_db
    restart: always
    volumes:
      - "./dbschema:/dbschema"
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    expose:
      - 5656
  app:
    build:
      context: .
      args:
        - PROJECT_NAME=${PROJECT_NAME}
    container_name: ${PROJECT_NAME}
    image: ${PROJECT_NAME}
    restart: always
    env_file:
      - .env
    depends_on:
      - db
